---


#    weight: 10
#    options:
#      - name: 'kernel.pid_max'
#        value: 4194303
#      - name: 'kernel.threads-max'
#        value: 2097152
#      - name: 'kernel.nmi_watchdog'
#        value: 0
#      - name: 'vm.max_map_count'
#        value: 524288
#      - name: 'net.ipv4.tcp_timestamps'
#        value: 0
#      - name: 'net.ipv4.tcp_sack'
#        value: 1
#      - name: 'net.core.netdev_max_backlog'
#        value: 261144
#      - name: 'net.ipv4.tcp_max_syn_backlog'
#        value: 8192
#      - name: 'net.ipv4.tcp_max_tw_buckets'
#        value: 262144
#      - name: 'net.ipv4.tcp_tw_reuse'
#        value: 1
#      - name: 'net.core.rmem_max'
#        value: 212992
#      - name: 'net.core.wmem_max'
#        value: 212992
#      - name: 'net.core.rmem_default'
#        value: 212992
#      - name: 'net.core.wmem_default'
#        value: 212992
#      - name: 'net.core.optmem_max'
#        value: 20480
#      - name: 'net.ipv4.tcp_rmem'
#        value: "4096 131072 6291456"
#      - name: 'net.ipv4.tcp_wmem'
#        value: "4096 16384 4194304"
#      - name: 'net.ipv4.tcp_low_latency'
#        value: 0
#      - name: 'net.ipv4.tcp_adv_win_scale'
#        value: 1
#      - name: 'net.ipv4.tcp_slow_start_after_idle'
#        value: 1
#      - name: 'net.ipv4.tcp_no_metrics_save'
#        value: 0
#      - name: 'net.ipv4.tcp_syncookies'
#        value: 1
#      - name: 'net.core.somaxconn'
#        value: 4096
#      - name: 'net.ipv4.tcp_ecn'
#        value: 2
#      - name: 'net.ipv4.conf.all.send_redirects'
#        value: 1
#      - name: 'net.ipv4.conf.all.accept_source_route'
#        value: 0
#      - name: 'net.ipv4.icmp_echo_ignore_broadcasts'
#        value: 1
#      - name: 'net.ipv4.tcp_no_metrics_save'
#        value: 0
#      - name: 'net.ipv4.tcp_slow_start_after_idle'
#        value: 1
#      - name: 'net.ipv4.tcp_fin_timeout'
#        value: 60
#      - name: 'net.netfilter.nf_conntrack_max'
#        value: 524288
#      - name: 'net.nf_conntrack_max'
#        value: 524288
#      - name: 'fs.file-max'
#        value: 26234859
#    # These settings can be managed in ceph-tunning.conf in ceph ansible, but since
#    # we do this in one file let's keep it that way
#      - name: 'vm.min_free_kbytes'
#        value: 4194303
#      - name: 'vm.vfs_cache_pressure'
#        value: 50
#      - name: 'vm.zone_reclaim_mode'
#        value: 0
#      - name: 'vm.dirty_ratio'
#        value: 10
#      - name: 'vm.dirty_background_ratio'
#        value: 3
#      - name: 'fs.inotify.max_user_watches'
#        value: 100000
#      - name: 'fs.inotify.max_user_instances'
#        value: 100000
#      - name: 'fs.file-max'
#        value: 124165 
#      - name: 'fs.inotify.max_queued_events'
#        value: 524288
#
#  - name: 'kernel-tunning'
#    weight: 10
#    options:
#      - name: 'net.bridge.bridge-nf-call-iptables'
#        value: 1
#      - name: 'net.ipv4.ip_forward'
#        value: 1
#      - name: 'net.ipv4.tcp_mtu_probing'
#        value: 1
#      - name: 'net.ipv4.conf.default.rp_filter'
#        value: 0
#      - name: 'net.ipv4.conf.all.rp_filter=0'
#        value: 0
#      - name: 'kernel.pid_max'
#        value: 4194303
#      - name: 'kernel.threads-max'
#        value: 2097152
#      - name: 'vm.max_map_count'
#        value: 524288
#      - name: 'net.ipv4.tcp_congestion_control'
#        value: 'cubic'
#      - name: 'net.ipv4.tcp_tw_reuse'
#        value: 1
#      - name: 'net.ipv4.tcp_max_tw_buckets'
#        value: 450000
#      - name: 'net.ipv4.tcp_fin_timeout'
#        value: 10
#      - name: 'net.ipv4.tcp_limit_output_bytes'
#        value: 131072
#      - name: 'net.core.busy_read'
#        value: 50
#      - name: 'net.core.busy_poll'
#        value: 50
#      - name: 'net.ipv4.tcp_fastopen'
#        value: 3
#      - name: 'kernel.numa_balancing'
#        value: 0
#      - name: 'kernel.sched_min_granularity_ns'
#        value: 10000000
#      - name: 'kernel.sched_migration_cost_ns'
#        value: 5000000
#      - name: 'vm.dirty_ratio'
#        value: 40
#      - name: 'vm.dirty_background_ratio'
#        value: 10
#      - name: 'net.ipv4.tcp_timestamps'
#        value: 0
#      - name: 'net.ipv4.tcp_sack'
#        value: 0
#      - name: 'net.ipv4.tcp_low_latency'
#        value: 1
#      - name: 'net.core.netdev_max_backlog'
#        value: 250000
#      - name: 'net.core.rmem_max'
#        value: 16777216
#      - name: 'net.core.wmem_max'
#        value: 16777216
#      - name: 'net.core.rmem_default'
#        value: 16777216
#      - name: 'net.core.wmem_default'
#        value: 16777216
#      - name: 'net.core.optmem_max'
#        value: 16777216
#      - name: 'net.ipv4.tcp_rmem'
#        value: '4096 87380 16777216'
#      - name: 'net.ipv4.tcp_wmem'
#        value: '4096 65536 16777216'
#
