resources__group_files:
  - dest: '/etc/rc.local'
    mode: '0755'
    content: |
      #!/bin/sh -e

      sleep 30
      # for that we need the following packages: linux-tools-common linux-cloud-tools-generic linux-tools-generic
      cpupower frequency-set --governor performance
      ethtool -G enp177s0f0np0 rx 2047 tx 2047
      ethtool -A enp177s0f0np0 autoneg off rx off tx off
      ethtool -G enp177s0f1np1 rx 2047 tx 2047
      ethtool -A enp177s0f1np1 autoneg off rx off tx off

  - dest: '/etc/netplan/50-cloud-init.yaml'
    mode: '0644'
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          enp177s0f0np0:
            dhcp4: no
            optional: true
          enp177s0f1np1:
            dhcp4: no
            optional: true
        bonds:
          bond0:
            interfaces: [ enp177s0f0np0, enp177s0f1np1 ]
            mtu: {{ mgmt_mtu }}
            parameters:
              mode: active-backup
        vlans:
          bond0.3002:
            id: 3002
            link: bond0
            mtu: {{ mgmt_mtu }}
            optional: true
            addresses:
            - {{ tunnel_address }}
          bond0.3003:
            id: 3003
            link: bond0
            mtu: {{ ceph_mtu }}
            optional: true
            addresses:
            - {{ ceph_internal_address }}
          bond0.3004:
            id: 3004
            link: bond0
            mtu: {{ ceph_mtu }}
            optional: true
            addresses:
            - {{ ceph_public_address }}
          bond0.3007:
            id: 3007
            link: bond0
            mtu: {{ mgmt_mtu }}
            addresses:
            - {{ octavia_address }}
            optional: true
        bridges:
          br0:
            optional: true
            addresses:
            - {{ ansible_host }}/22
            gateway4: {{ mgmt_gateway }}
            nameservers:
              addresses:
              - 8.8.8.8
              - 8.8.4.4
            interfaces: [ bond0 ]
            mtu: {{ mgmt_mtu }}
            parameters:
              stp: false

