---
netbase_domain: 'cloudpoint.tcpro.cz'
netbase__enabled: True
netbase__default_hosts:
  - '127.0.1.1': [ '{{inventory_hostname}}','{{inventory_hostname_short}}' ]
  - '127.0.0.1': [ 'localhost' ]
  - '{{hostvars["master01"].ansible_host}}' : ['{{hostvars["master01"].inventory_hostname}}', '{{hostvars["master01"].inventory_hostname_short}}']