sysctl__group_parameters:
  - name: 'global-tunning'
    weight: 10
    options:
      - name: 'fs.file-max'
        value: 1000000

      - name: 'net.core.somaxconn'
        value: 32768

      - name: 'net.ipv4.tcp_max_syn_backlog'
        value: 8192

      - name: 'net.ipv4.tcp_tw_reuse'
        value: 1

      - name: 'vm.dirty_background_ratio'
        value: 5

      - name: 'vm.dirty_ratio'
        value: 10

      - name: 'net.ipv4.tcp_mem'
        value: '4096 87380 16777216'

      - name: 'net.ipv4.tcp_rmem'
        value: '4096 87380 134217728'

      - name: 'net.ipv4.tcp_wmem'
        value: '4096 87380 134217728'

      - name: 'kernel.pid_max'
        value: 4194303

      - name: 'kernel.threads-max'
        value: 2097152

      - name: 'kernel.nmi_watchdog'
        value: 1

      - name: 'vm.min_free_kbytes'
        value: 4194303

      - name: 'vm.vfs_cache_pressure'
        value: 50

      - name: 'vm.zone_reclaim_mode'
        value: 0

      - name: 'fs.inotify.max_user_watches'
        value: 100000

      - name: 'fs.inotify.max_user_instances'
        value: 100000

      - name: 'fs.inotify.max_queued_events'
        value: 524288
